language: ruby
sudo: false
cache: bundler
before_install:
  - gem update --system
  - gem install bundler
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - jruby-9.1.17.0
gemfile:
  - gemfiles/activesupport4.gemfile
  - gemfiles/activesupport5.gemfile
